function setParticlesHeight(){const particlesContainer=document.getElementById('particles-js');if(particlesContainer){particlesContainer.style.height=Math.max(window.innerHeight,document.body.scrollHeight)+'px'}}
function startParticles(){particlesJS('particles-js',{"particles":{"number":{"value":120,"density":{"enable":!0,"value_area":1500}},"color":{"value":"#4a4a54"},"shape":{"type":"circle","stroke":{"width":0,"color":"#000"}},"opacity":{"value":0.5,"random":!0},"size":{"value":2,"random":!0},"line_linked":{"enable":!0,"distance":150,"color":"#4a4a54","opacity":0.4,"width":1},"move":{"enable":!0,"speed":0.8,"direction":"none","random":!0,"straight":!1,"out_mode":"bounce","bounce":!0,"attract":{"enable":!1}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":!0,"mode":"grab"},"onclick":{"enable":!1,"mode":"push"},"resize":!0},"modes":{"grab":{"distance":150,"line_linked":{"opacity":0.6}},"bubble":{"distance":400,"size":40,"duration":2,"opacity":8,"speed":3},"repulse":{"distance":200,"duration":0.4},"push":{"particles_nb":4},"remove":{"particles_nb":2}}},"retina_detect":!0})}(function addSmoothMouseAttract(){let mouse={x:null,y:null};let smoothMouse={x:null,y:null};let isOverCanvas=!1;const smoothing=0.12;const particlesEl=document.getElementById('particles-js');let canvas=null;function updateCanvasRef(){if(particlesEl){canvas=particlesEl.querySelector('canvas')}}
setTimeout(updateCanvasRef,500);document.addEventListener('mousemove',function(e){if(!canvas)return;const rect=canvas.getBoundingClientRect();const dpr=window.devicePixelRatio||1;if(e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom){mouse.x=(e.clientX-rect.left)*dpr;mouse.y=(e.clientY-rect.top)*dpr;isOverCanvas=!0}else{isOverCanvas=!1}});if(particlesEl){particlesEl.addEventListener('mouseleave',function(){isOverCanvas=!1});particlesEl.addEventListener('mouseenter',function(){isOverCanvas=!0})}
function animateSmoothMouse(){if(isOverCanvas&&mouse.x!==null&&mouse.y!==null){if(smoothMouse.x===null||smoothMouse.y===null){smoothMouse.x=mouse.x;smoothMouse.y=mouse.y}else{smoothMouse.x+=(mouse.x-smoothMouse.x)*smoothing;smoothMouse.y+=(mouse.y-smoothMouse.y)*smoothing}
if(window.pJSDom&&window.pJSDom[0]&&window.pJSDom[0].pJS){window.pJSDom[0].pJS.interactivity.mouse.pos_x=smoothMouse.x;window.pJSDom[0].pJS.interactivity.mouse.pos_y=smoothMouse.y;window.pJSDom[0].pJS.interactivity.status='mousemove'}}else{if(window.pJSDom&&window.pJSDom[0]&&window.pJSDom[0].pJS){window.pJSDom[0].pJS.interactivity.mouse.pos_x=null;window.pJSDom[0].pJS.interactivity.mouse.pos_y=null;window.pJSDom[0].pJS.interactivity.status='mouseleave'}}
requestAnimationFrame(animateSmoothMouse)}
animateSmoothMouse()})();document.addEventListener('DOMContentLoaded',()=>{setParticlesHeight();startParticles();setTimeout(()=>{setParticlesHeight();if(window.pJSDom&&window.pJSDom[0]&&window.pJSDom[0].pJS){window.pJSDom[0].pJS.fn.canvasSize()}},100)});window.addEventListener('resize',()=>{setParticlesHeight();if(window.pJSDom&&window.pJSDom[0]&&window.pJSDom[0].pJS){window.pJSDom[0].pJS.fn.canvasSize()}});window.addEventListener('scroll',setParticlesHeight);document.addEventListener("DOMContentLoaded",function(){AOS.init({duration:800,easing:'ease-in-out',once:!1,mirror:!0});const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('show');const sectionTitle=entry.target.querySelector('.section-title');if(sectionTitle){sectionTitle.classList.add('show')}}else{if(!entry.target.classList.contains('intro')){entry.target.classList.remove('show')}}})},{threshold:0.15});const hiddenElements=document.querySelectorAll('.hidden');hiddenElements.forEach((el)=>observer.observe(el));const navbar=document.querySelector('.navbar');if(navbar){window.addEventListener('scroll',()=>{if(window.scrollY>50){navbar.classList.add('scrolled')}else{navbar.classList.remove('scrolled')}})}
document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();const targetId=this.getAttribute('href');const targetElement=document.querySelector(targetId);if(targetElement){window.scrollTo({top:targetElement.offsetTop-70,behavior:'smooth'})}})});window.addEventListener('scroll',()=>{const sections=document.querySelectorAll('section');let current='';sections.forEach((section)=>{const sectionTop=section.offsetTop-100;const sectionHeight=section.clientHeight;if(window.scrollY>=sectionTop&&window.scrollY<sectionTop+sectionHeight){current=section.getAttribute('id')}});document.querySelectorAll('.nav-link').forEach((link)=>{link.classList.remove('active');if(link.getAttribute('href').includes(current)){link.classList.add('active')}})})});document.addEventListener("DOMContentLoaded",()=>{const themeToggle=document.getElementById("theme-toggle");const htmlElement=document.documentElement;function setTheme(theme){htmlElement.setAttribute("data-theme",theme);localStorage.setItem("theme",theme);setTimeout(()=>{document.body.classList.remove("theme-transition")},1000)}
function toggleTheme(){const currentTheme=htmlElement.getAttribute("data-theme")||"dark";const newTheme=currentTheme==="dark"?"light":"dark";setTheme(newTheme)}
const savedTheme=localStorage.getItem("theme");const prefersDark=window.matchMedia("(prefers-color-scheme: dark)").matches;if(savedTheme){setTheme(savedTheme)}else{setTheme(prefersDark?"dark":"light")}
if(themeToggle){themeToggle.addEventListener("click",(e)=>{e.preventDefault();toggleTheme();themeToggle.style.transform="scale(0.8)";setTimeout(()=>{themeToggle.style.transform=""},200)});const svgElements=themeToggle.querySelectorAll('svg');svgElements.forEach(svg=>{svg.addEventListener('click',(e)=>{e.stopPropagation();themeToggle.click()});const paths=svg.querySelectorAll('path');paths.forEach(path=>{path.addEventListener('click',(e)=>{e.stopPropagation();themeToggle.click()})})})}
window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",(e)=>{if(!localStorage.getItem("theme")){setTheme(e.matches?"dark":"light")}});function updateProfileVector(){const theme=htmlElement.getAttribute("data-theme")||"dark";const vectorImg=document.querySelector('.profile-photo-vector');if(vectorImg){if(theme==="light"){vectorImg.src="images/vektorel-beyaz.webp";vectorImg.srcset="images/vektorel-beyaz-small.webp 400w, images/vektorel-beyaz.webp 800w"}else{vectorImg.src="images/vektorel-siyah.webp";vectorImg.srcset="images/vektorel-siyah-small.webp 400w, images/vektorel-siyah.webp 800w"}}}
updateProfileVector();if(themeToggle){themeToggle.addEventListener("click",()=>{setTimeout(updateProfileVector,10)})}
window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",()=>{setTimeout(updateProfileVector,10)})});document.addEventListener("DOMContentLoaded",function(){const phrases=["junior developer","software enthusiast","web designer","AI/ML enthusiast","computer engineer","ww2 history buff"];const typingSpeed=80;const erasingSpeed=40;const delayBetweenPhrases=1500;let phraseIndex=0;let charIndex=0;let isTyping=!0;const textElement=document.getElementById("typing-text");function typeText(){if(isTyping){if(charIndex<phrases[phraseIndex].length){textElement.textContent+=phrases[phraseIndex].charAt(charIndex);charIndex++;setTimeout(typeText,typingSpeed)}else{isTyping=!1;setTimeout(typeText,delayBetweenPhrases)}}else{if(charIndex>0){textElement.textContent=phrases[phraseIndex].substring(0,charIndex-1);charIndex--;setTimeout(typeText,erasingSpeed)}else{isTyping=!0;phraseIndex=(phraseIndex+1)%phrases.length;setTimeout(typeText,typingSpeed)}}}
typeText();const animatedTitle=document.querySelector('.animated-title');if(animatedTitle){animatedTitle.classList.add('show')}});document.addEventListener('DOMContentLoaded',function(){const navbarToggler=document.querySelector('.navbar-toggler');const navbarCollapse=document.querySelector('.navbar-collapse');const navLinks=document.querySelectorAll('.nav-link');if(navbarToggler&&navbarCollapse){navbarToggler.addEventListener('click',function(){const isExpanded=navbarCollapse.classList.contains('show');navbarCollapse.classList.toggle('show');navbarToggler.setAttribute('aria-expanded',!isExpanded)});navLinks.forEach(link=>{link.addEventListener('click',function(){navbarCollapse.classList.remove('show');navbarToggler.setAttribute('aria-expanded','false')})});document.addEventListener('click',function(event){const isClickInsideNav=navbarToggler.contains(event.target)||navbarCollapse.contains(event.target);if(!isClickInsideNav&&navbarCollapse.classList.contains('show')){navbarCollapse.classList.remove('show');navbarToggler.setAttribute('aria-expanded','false')}})}});window.addEventListener('scroll',function(){const scrollProgress=document.querySelector('.scroll-progress');if(scrollProgress){const windowHeight=document.documentElement.scrollHeight-document.documentElement.clientHeight;const scrolled=(window.scrollY/windowHeight)*100;scrollProgress.style.width=scrolled+'%';scrollProgress.style.opacity=window.scrollY>0?'1':'0'}});setTimeout(()=>{console.clear();console.log(`%c

  █  █▀  ▄   ███   ▄█ █    ██   ▄█    ▄▄▄▄▄    ▄ ▄   ▄████
  █▄█     █  █  █  ██ █    █ █  ██   █     ▀▄ █   █  █▀   ▀
  █▀▄  █   █ █ ▀ ▄ ██ █    █▄▄█ ██ ▄  ▀▀▀▀▄  █ ▄   █ █▀▀
  █  █ █   █ █  ▄▀ ▐█ ███▄ █  █ ▐█  ▀▄▄▄▄▀   █  █  █ █
    █  █▄ ▄█ ███    ▐     ▀   █  ▐            █ █ █   █
   ▀    ▀▀▀                  █                 ▀ ▀     ▀
                            ▀
    `,"color: red;");console.log(`Check my GitHub for more cool stuff: %chttps://github.com/kubilaiswf`,"color: red; text-decoration: underline;")},500)
